config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tweeps
  root "tweeps#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweep.rb
class Tweep < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweeps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controler.rb
class RegistrationsController < Devise::RegistrationsController


    private 

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


    private 

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/tweeps_controller.rb
class TweepsController < ApplicationController
  before_action :set_tweep, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  
  # GET /tweeps or /tweeps.json
  def index
    @tweeps = Tweep.all.order("created_at DESC")
    @tweep = Tweep.new
  end

  # GET /tweeps/1 or /tweeps/1.json
  def show
  end

  # GET /tweeps/new
  def new
    @tweep = current_user.tweeps.build
  end

  # GET /tweeps/1/edit
  def edit
  end

  # POST /tweeps or /tweeps.json
  def create
    @tweep = current_user.tweeps.build(tweep_params)

    respond_to do |format|
      if @tweep.save
        format.html { redirect_to root_path, notice: "Tweep was successfully created." }
        format.json { render :show, status: :created, location: @tweep }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeps/1 or /tweeps/1.json
  def update
    respond_to do |format|
      if @tweep.update(tweep_params)
        format.html { redirect_to @tweep, notice: "Tweep was successfully updated." }
        format.json { render :show, status: :ok, location: @tweep }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeps/1 or /tweeps/1.json
  def destroy
    @tweep.destroy
    respond_to do |format|
      format.html { redirect_to tweeps_url, notice: "Tweep was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweep
      @tweep = Tweep.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweep_params
      params.require(:tweep).permit(:tweep)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeps_helper.rb
module TweepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweepy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div id="flash" class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div id="flash" class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Tweepy</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="field is-grouped ">
            <p class="control">
              <%= link_to "New Tweep", root_path, class: "button is-info is-inverted" %>
            </p>
            <% if user_signed_in? %>
            <p class="control">
              <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
            </p>
            <p class="control">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %>
            </p>
            <% else %>
            <p class="control">
              <%= link_to "Sign Up", new_user_registration_path, class: "button is-info" %>
            </p>
            <p class="control">
              <%= link_to "Sign In", new_user_session_path, class: "button is-info" %>
            </p>
            <% end %>
          </div>
        </div>
      </div>

    </nav>
    <%= yield %>
    <script type="text/javascript">
      setTimeout(() => {
        document.getElementById("flash").style.display = "none";
      }, 3000);
  </script>
  </body>
  
</html>

app/views/tweeps/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
                <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name ) %>
            </p>
        </figure>
        <div class="media-content">
            <%= render 'tweeps/form' %>
        </div>
    </article>
    <% end %>


<% @tweeps.each do | tweep | %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <%= gravatar_image_tag(tweep.user.email, size: 64, alt: tweep.user.name ) %>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong><%= tweep.user.name %></strong><br>
                    <small>@<%= tweep.user.username %></small><br>
                    <p><%= tweep.tweep %></p>
                </div>
                <% if user_signed_in? && current_user == tweep.user %>
                <nav class="level">
                    <div class="level-left is-mobile">
                        <%= link_to tweep, class: "level-item" do %>
                            <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>     
                        <% end %>
                        <%= link_to edit_tweep_path(tweep), class: "level-item" do %>
                            <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>     
                        <% end %>
                        <%= link_to tweep, method: :delete, data: { confirm: "Are you sure?" } do %>
                            <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>     
                        <% end %>
                    </div>
                </nav>
                <% end %>
            </div>
        </article>
    </div>
<% end %>

</div>

app/views/tweeps/_form.html.erb
<%= simple_form_for(@tweep) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :tweep, label: "Tweep about it!", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label" }, placeholder: "Compose a new Tweep...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/tweeps/_profile.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Profile</p>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name ) %>
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong><%= current_user.name %></strong> <br />
                            <small><%= current_user.username %></small>
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <div class="panel-block">
            <div class="level is-mobile">
                <div class="level-item has-centered-text">
                    <div>
                        <p class="heading">Tweeps</p>
                        <p class="title is-6"><%= current_user.tweeps.count %></p>
                    </div>
                </div>
                <div class="level-item has-centered-text">
                    <div>
                        <p class="heading">Following</p>
                        <p class="title is-6">123</p>
                    </div>
                </div>
                <div class="level-item has-centered-text">
                    <div>
                        <p class="heading">Followers</p>
                        <p class="title is-6">456</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

app/views/tweeps/_trends.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Trends</p>
        <a class="panel-block">
            Trend 1
        </a>
        <a class="panel-block">
            Trend 2
        </a>
        <a class="panel-block">
            Trend 3
        </a>
        <a class="panel-block">
            Trend 4
        </a>
        <a class="panel-block">
            Trend 5
        </a>
        <a class="panel-block">
            Trend 6
        </a>
        <a class="panel-block">
            Trend 6
        </a>        
    </nav>
</div>

app/views/tweeps/_who_to_follow.html.erb
<div class="column">
    <nav class="panel">
        <p class="panel-heading">Who to Follow</p>

    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/64x64.png" alt="Placeholder image.">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>John Smith</strong>
                        <small>@johnsmith</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/64x64.png" alt="Placeholder image.">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>John Smith</strong>
                        <small>@johnsmith</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/64x64.png" alt="Placeholder image.">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>John Smith</strong>
                        <small>@johnsmith</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
    </nav>
</div>

app/views/tweeps/edit.html.erb
<h1>Editing Tweep</h1>

<%= render 'form', tweep: @tweep %>

<%= link_to 'Show', @tweep %> |
<%= link_to 'Back', tweeps_path %>

app/views/tweeps/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
    <% if user_signed_in? %>
      <%= render 'profile' %>
    <% else %>
      <%= render 'trends' %>
    <% end %>
      <%= render 'feed' %>
      <%= render 'who_to_follow' %>
    </div>
  </div>
</section>

app/views/tweeps/new.html.erb
<h1>New Tweep</h1>

<%= render 'form', tweep: @tweep %>

<%= link_to 'Back', tweeps_path %>

app/views/tweeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweep:</strong>
  <%= @tweep.tweep %>
</p>

<%= link_to 'Edit', edit_tweep_path(@tweep) %> |
<%= link_to 'Back', tweeps_path %>